"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from math import sqrt

def is_hex(t):
    x = 1 + sqrt(8 * t + 1)
    n = x / 4
    return n - int(n) == 0

def is_pent(t):
    return sqrt(24 * t + 1) % 6 == 5

def get_tri(t):
    return t * (t + 1)/2

def next_tri():
    t = 286
    found = False
    while not found:
        tri = get_tri(t)
        if is_pent(tri):
            if is_hex(tri):
                return tri
        t += 1

# test
print(is_hex(44)==False)
print(is_hex(40755))
print(is_pent(40755))
print(get_tri(285)==40755)

# solution
print(next_tri())